namespace RogueDeck.Run;

// THE ACT BECOMES A MAP A RUN CAN WALK (map rework S11).
//
// Everything up to here is an ACT: rows, slots, edges, strands and a role per room. A run needs a RunMap — nodes
// with a type and a payload, edges, entries — and the rooms need CONTENT: which fight stands in this elite, which
// door this event opens. None of that changed with the new generator, and none of it is rewritten here.
//
// So the content half of `MapGenerationSpec` is still the authority (§4 of the plan: "MapNodeRealizer is reused
// verbatim"), and the two selections that decide what a room really holds — the fight, drawn against the balance
// targets without replacement, and the authored node ref, drawn from its pool without replacement — are the
// rule-based generator's own, called rather than copied. An act generated by either generator therefore holds the
// same content drawn by the same rules; what differs is the shape it is arranged in, which is the entire point.
//
// AND THE LAYOUT IS WRITTEN DOWN. The strategic topology guarantees that its edges do not cross when each row is
// drawn in column order (S4), and a guarantee nobody records is a guarantee the frontends cannot keep: without a
// layout they lay a row out in the order its nodes were added. So every room's column and row go into
// `RunMap.Layout`, and the picture on screen is the picture the generator promised.
public static class StrategicMapRealizer
{
    public static GeneratedMap Realize(
        GeneratedAct act,
        MapGenerationSpec content,
        int startingLoadout,
        BalanceCalculator balance,
        Func<MapNodeKind, MapCoord, EncounterId?, string?, NodeContent> realize)
    {
        ArgumentNullException.ThrowIfNull(act);
        ArgumentNullException.ThrowIfNull(content);
        ArgumentNullException.ThrowIfNull(balance);
        ArgumentNullException.ThrowIfNull(realize);

        var topology = act.Topology;
        var rows = topology.Rows.Count;
        var selector = new EncounterSelector(content.Encounters, balance);

        // The CONTENT stream of the attempt this act actually came from — so an act that needed three tries draws
        // its fights from the streams of the third try, and a resumed run walks into the same rooms.
        var rng = new MapGenRandom(MapSeedStreams.From(act.Seed).Attempt(act.Attempt).Content);

        // Drawn without replacement across the whole act, exactly as the rule-based generator does it: a run does
        // not meet the same fight or open the same door twice until a pool runs out.
        var usedEncounters = new HashSet<EncounterId>();
        var usedRefs = new HashSet<string>();

        var builder = new RunMapBuilder();
        var roles = new Dictionary<NodeId, MapNodeKind>();

        foreach (var row in topology.Rows)
            foreach (var slot in row.Slots)
            {
                var kind = act.Plan.KindOf(slot.Id);

                // A treasure that bites back. The roll is taken on every treasure whether or not the act has
                // mimics to offer, so that adding one to the pools later does not shift every other room's draw.
                // There is no guarantee row to exempt here — the strategic generator promises nothing per route
                // that a mimic could quietly break (the floor of challenge counts a mimic as the fight it is).
                if (kind == MapNodeKind.Treasure && content.TreasureMimicChancePercent > 0
                    && rng.Next(100) < content.TreasureMimicChancePercent
                    && selector.HasCandidates(MapNodeKind.Mimic))
                {
                    kind = MapNodeKind.Mimic;
                }

                var encounter = RuleBasedMapGenerator.SelectEncounter(
                    kind, row.Index, rows, content, selector, startingLoadout, rng, usedEncounters);
                var nodeRef = RuleBasedMapGenerator.SelectNodeRef(kind, content, row.Index, rows, rng, usedRefs);
                var realized = realize(kind, new MapCoord(row.Index, slot.Column), encounter, nodeRef);

                builder.AddNode(slot.Id, realized.Type, realized.Payload, realized.Tags);
                builder.Position(slot.Id, slot.Column, row.Index);
                roles[slot.Id] = kind;
            }

        foreach (var entry in topology.EntryIds)
            builder.Entry(entry);
        foreach (var edge in topology.Edges)
            builder.Connect(edge.From, edge.To);

        return new GeneratedMap(builder.Build(), roles);
    }
}
