<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\RogueDeck.Core\RogueDeck.Core.csproj" />
    <ProjectReference Include="..\RogueDeck.Scenario\RogueDeck.Scenario.csproj" />
    <ProjectReference Include="..\RogueDeck.Sandbox.Combat\RogueDeck.Sandbox.Combat.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
