<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RogueDeck.Bot</RootNamespace>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RogueDeck.Sandbox.Run\RogueDeck.Sandbox.Run.csproj" />
  </ItemGroup>

</Project>
